### ISSUE TITLE
all examples are not found

### ISSUE THREAD

**Issue by kangnixi** [uniprank/ngx-file-uploader#1]
Hi

I visited examples in readme, the pages told me that not found

**Comment by Denfie** [comment]
Yeah I will upload the example files later. You can take a look how it look like here.
[Example](https://uniprank.github.io/ng2-file-uploader/example/advanced)

**Comment by megalucio** [comment]
Examples still not working

**Comment by fromage9747** [comment]
Examples still not working.  Keen to use this but would like to see a working example first as the screenshot looks good.

**Comment by Denfie** [comment]
example page is now working: [Example](https://uniprank.github.io/ngx-file-uploader#test-case-1)
