### ISSUE TITLE
Error with AOT in angular 4

### ISSUE THREAD

**Issue by shahzadhassan** [uniprank/ngx-file-uploader#3]
I am trying to create a deployment for my angular 4 application but the FileUploaderModule is throwing an error with AOT compilation.
ng build --prod --aot

ERROR in Unexpected value 'undefined' exported by the module 'FileUploaderModule in */node_modules/@uniprank/ngx-file-uploader/typings/index.d.ts'

package.json
{
  "name": "test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/forms": "^4.1.2",
    "@angular/http": "^4.1.2",
    "@angular/platform-browser": "^4.1.2",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/platform-server": "^4.1.2",
    "@angular/router": "^4.1.2",
    "@types/lodash": "^4.14.63",
    "@uniprank/ngx-file-uploader": "^4.1.3-Beta",
    "angular2-busy": "^2.0.4",
    "angular2-fontawesome": "~0.9.0",
    "angular2-signature-pad": "^1.0.2",
    "bootstrap": "^4.0.0-alpha.6",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "font-awesome": "~4.7.0",
    "lodash": "^4.17.4",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-validation": "^4.2.0",
    "ngx-bootstrap": "^1.6.6",
    "ngx-infinite-scroll": "^0.5.1",
    "ngx-malihu-scrollbar": "^1.1.2",
    "ngx-pipes": "^1.6.1",
    "ngx-ui-switch": "^1.3.5",
    "rxjs": "^5.4.0",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.9"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.3",
    "@angular/compiler": "^4.1.2",
    "@angular/compiler-cli": "^4.1.2",
    "@types/jasmine": "2.5.38",
    "@types/node": "7.0.15",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.5.0",
    "protractor": "~5.1.0",
    "raw-loader": "^0.5.1",
    "rollup": "^0.41.6",
    "rollup-plugin-commonjs": "^8.0.2",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-uglify": "^2.0.1",
    "sass-loader": "^6.0.3",
    "ts-node": "3.0.2",
    "tslint": "5.1.0",
    "typescript": "^2.3.2"
  }
}

**Comment by xuemingfeng** [comment]
I have the same error. :(

**Comment by glr91** [comment]
I have the same problem. Any ideas on how to fix it?

**Comment by glr91** [comment]
I have seen [here](https://stackoverflow.com/questions/39173159/error-unexpected-value-undefined-exported-by-the-module-dynamicformmodule) that this kind of error may appear due to repeated exports. In the file `index.d.ts` some directives are exported, but I think that they have been previously exported in `public_api.d.ts`. May this have some relation with this bug?

**Comment by ghost** [comment]
Possible fix: I clone the repo and replace al de "../folder" imports with "../folder/file(.ts)". Now it does compile AoT, but its not compatible yet with Universal, cause it uses directly some Browser objects.

**Comment by harrise** [comment]
Anybody resolve this?

**Comment by harrise** [comment]
tried including nxfileuploader.js in my app: https://github.com/angular/angular/issues/19757

**Comment by Denfie** [comment]
New version which is compatible with the newest angular version. UMD library
